spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liminlei/config-repo
          username: liminlei
          password: Daohaode\qusi8
          basedir: E:\workspace\IDEASpace\MicoServiceLearn\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
         include: "*"

#docker run -d --hostname my-rabbit -p 5672:5672 -p 15672:15672 rabbitmq:3.7.3-management