spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liminlei/config-repo
          username: liminlei
          password: Daohaode\qusi8
          basedir: E:\workspace\IDEASpace\MicoServiceLearn\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/